# Generated by Django 4.2 on 2025-11-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_pokemon_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='tipo',
            field=models.CharField(choices=[('A', 'Agua'), ('F', 'Fuego'), ('T', 'Tierra'), ('P', 'Planta'), ('E', 'Eléctrico'), ('L', 'Lagartija')], max_length=1),
        ),
    ]
