# Generated by Django 4.2 on 2025-11-03 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_alter_pokemon_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='entrenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.entrenador'),
        ),
    ]
