# Generated by Django 5.2.8 on 2025-12-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_pokemon_entrenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='entrenadores'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='tipo',
            field=models.CharField(choices=[('A', 'Agua'), ('P', 'Planta'), ('L', 'Lagartija'), ('T', 'Tierra'), ('F', 'Fuego'), ('E', 'Eléctrico')], max_length=1),
        ),
    ]
