# Generated by Django 5.2.8 on 2026-01-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_entrenador_foto_alter_pokemon_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='tipo',
            field=models.CharField(choices=[('Agua', 'Agua'), ('Fuego', 'Fuego'), ('Tierra', 'Tierra'), ('Planta', 'Planta'), ('Eléctrico', 'Eléctrico'), ('Lagartija', 'Lagartija')], max_length=15),
        ),
    ]
